name: pr_build
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install --upgrade pip
    - run: pip install -e ".[dev]"
    - run: black --check --diff -l 120 src/topbid/ tests/
    - run: pylint src/topbid/ tests/
